// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NWT_2.Data;

namespace NWT_2.Migrations
{
    [DbContext(typeof(GradesContext))]
    partial class GradesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NWT_2.Models.GradesEF", b =>
                {
                    b.Property<string>("No")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("averageRating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("bio")
                        .HasColumnType("int");

                    b.Property<int>("chem")
                        .HasColumnType("int");

                    b.Property<int>("math")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("phys")
                        .HasColumnType("int");

                    b.Property<int>("rule")
                        .HasColumnType("int");

                    b.Property<int>("serb")
                        .HasColumnType("int");

                    b.HasKey("No");

                    b.ToTable("SGradesEF");
                });
#pragma warning restore 612, 618
        }
    }
}
